import { NextResponse } from 'next/server';
import { prisma } from 'database';

export async function POST(request: Request) {
  try {
    const { accountId } = await request.json();

    if (!accountId) {
      return NextResponse.json({ error: 'Missing accountId' }, { status: 400 });
    }

    // Generate random quota 0-100
    const quotaPercent = Math.floor(Math.random() * 101);
    let status = 'Green';
    if (quotaPercent < 20) status = 'Red';
    else if (quotaPercent < 50) status = 'Yellow';

    const result = await prisma.$transaction(async (tx: any) => {
      const updatedStatus = await tx.quotaStatus.update({
        where: { accountId },
        data: {
          quotaPercent,
          status,
          source: 'Mock',
          lastCheckedAt: new Date(),
        },
      });

      await tx.quotaHistory.create({
        data: {
          accountId,
          quotaPercent,
          status,
          source: 'Mock',
          note: 'Generated by mock refresh',
        },
      });

      return updatedStatus;
    });

    return NextResponse.json(result);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
